service: find_interesting_things

provider:
  name: aws
  region: us-east-1
  runtime: python3.8

functions:
  infer:
    handler: make_map.find_interesting_things
    timeout: 30
    events:
      - http:
          path: find
          method: post

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true

package:
  exclude:
    - node_modules/**
    - venv/**
